language: python
python:
  - 3.8
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-gi
  - sudo apt-get install python3-tk
  - sudo apt install python-pytest
  - pip install -r requirements.txt
  - pip3 install --upgrade pip
  - pip3 install pytest
# command to run tests
script:
  - python3 -m pytest tests/*
