language: python
python:
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-gi
  - pip install -r requirements.txt
  - pip3 install --upgrade pip
# command to run tests
script:
  - python3 -m pytest tests/*
